---
- name: Create index.html from template
  hosts: all
  tasks:
  - name: Create index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: vagrant
      group: vagrant
      mode: 0644